feat:[sho-59] Add Shop page with filter
shopperlabs/demo.laravelshopper.dev pull request #29
Opened 2024-11-21 18:07 UTC by cybersoldattech

2024-11-22 08:08 UTC, StevyMarlino requested changes

2024-11-22 08:08 UTC, StevyMarlino commented on app/Livewire/Pages/Store.php
> +    private $products; // @phpstan-ignore-line
il faut preciser le type de la variable $product

2024-11-22 08:08 UTC, StevyMarlino commented on app/Models/Product.php
> +    }
tu as essayer de voir dans le model parent les fonction définit si ceci n'existe pas encore ?

2024-11-22 08:08 UTC, StevyMarlino commented on resources/views/components/layouts/header.blade.php
> +                <x-nav.item link="{{ route('shop.products') }}">{{ __('Shop') }}</x-nav.item>
```suggestion
                <x-nav.item link="{{ route('shop.products') }}">{{ __('Store') }}</x-nav.item>
```

2024-11-22 08:08 UTC, StevyMarlino commented on resources/views/livewire/pages/store.blade.php
> +                                                        </div>
N'oublie pas wire:key

2024-11-22 08:08 UTC, StevyMarlino commented on routes/web.php
> +Route::get('/shop', Pages\Store::class)->name('shop.products');
```suggestion
Route::get('/store', Pages\Store::class)->name('store.products');
```

2024-11-22 08:09 UTC, StevyMarlino commented
Je n'ai pas vu de test ! tu taffe encore dessus ?

2024-11-22 17:43 UTC, cybersoldattech commented on app/Models/Product.php
> +    }
Oui

2024-11-25 00:55 UTC, StevyMarlino requested changes

2024-11-25 00:55 UTC, StevyMarlino commented on app/Livewire/Pages/Store.php
> +        $this->atributes = Attribute::with('values')->where('is_enabled', true)->get();
```suggestion
        $this->atributes = Attribute::with('values')->enabled()->get();
```
Le scope enabled est deja defini dans le model attribute

2024-11-25 08:49 UTC, cybersoldattech commented on app/Livewire/Pages/Store.php
> +        $this->atributes = Attribute::with('values')->where('is_enabled', true)->get();
c'est fait

2024-11-29 14:02 UTC, mckenziearts requested changes
Applique les modifications expliquées

2024-11-29 14:23 UTC, merged