Feature/sho 42 review dun produit
shopperlabs/demo.laravelshopper.dev pull request #30
Opened 2024-11-25 00:24 UTC by StevyMarlino

2024-11-25 08:55 UTC, mckenziearts requested changes

2024-11-25 08:55 UTC, mckenziearts commented on app/Actions/Product/AddReview.php
> +    public function execute(Model $reviewrateable, array $data, Model $author): \Shopper\Core\Models\Review
Importe  le classe en haut, et la classe a importer pour `$author` c'est `User` et non `Model`

2024-11-25 08:55 UTC, mckenziearts commented on app/Actions/Product/AddReview.php
> +final class AddReview
Renomme la classe pour qu'elle puisse être un peu plus expressive `AddProductReviewAction`

2024-11-25 08:55 UTC, mckenziearts commented on app/Livewire/Modals/Product/ModalProduct.php
> +final class ModalProduct extends ModalComponent
Renomme la classe en AddProductReview

2024-11-25 08:55 UTC, mckenziearts commented on app/Livewire/Forms/ProductReviewsForm.php
> +    public ?int $rating = 1;
Tu as déjà mit une valeur par défaut donc plus besoin de mettre `?` devant.

2024-11-25 08:55 UTC, mckenziearts commented on app/Livewire/Pages/Product/ProductReviews.php
> +    public function reviewBasOn(): void
Que doit faire cette fonction? Parce qu'à son nom je sais pas trop à quoi m'attendre

2024-11-25 08:55 UTC, mckenziearts commented on app/Livewire/Pages/Product/SingleProduct.php
Pourquoi l'avoir déplacer dans un dossier Product ?

2024-11-25 08:55 UTC, mckenziearts commented on app/Livewire/ReviewsList.php
> +class ReviewsList extends SlideOverComponent
Les slides-over et sont considérés comme des modals donc doivent être dans le dossier `Modals`

2024-11-25 08:55 UTC, mckenziearts commented on app/Livewire/ReviewsList.php
> +        $this->averageRating = floatval($this->product->averageRating()[0]) ?? $this->averageRating;
Sauf me tromper j'ai l'impression que tu fais ce calcul 2 fois. Faut créer un trait pour l'appeler dans chaque composant ou tu en as besoin

2024-11-25 08:55 UTC, mckenziearts commented on resources/views/livewire/pages/product/single-product.blade.php
> +                                    <div
Qu'est e qu'il y'a eu comme modification ici ?

2024-11-25 08:55 UTC, mckenziearts commented on resources/views/livewire/pages/product/single-product.blade.php
> +            <livewire:pages.product.product-reviews :product="$product" />
y'a trop de `product` surtout que c'est pas sensé être une page. On appelle pas les pages dans des pages. ton composant devrait être `livewire:components.product.reviews`

2024-11-25 08:55 UTC, mckenziearts commented on resources/views/livewire/reviews-list.blade.php
> +                            {{ __('😱 Oops! Your review list is empty') }}
Pas `Your review` il s'agit de reviews de produits pas de review d'un utilisateur. Donc le message devrait etre du style `Ce produit n'a pas encore reçu d'avis` (en anglais)

2024-11-25 08:55 UTC, mckenziearts commented on routes/web.php
> +Route::get('/products/{slug}', Pages\Product\SingleProduct::class)->name('single-product');
Ce changement n'est pas nécessaire tu peux reset cette modification

2024-11-25 20:08 UTC, StevyMarlino commented on app/Livewire/Pages/Product/ProductReviews.php
> +    public function reviewBasOn(): void
juste pour update la views a chaque nouvelle création de review

2024-11-25 20:10 UTC, StevyMarlino commented on app/Livewire/ReviewsList.php
> +class ReviewsList extends SlideOverComponent
comme ca revient a manage les produits j ai trouver judicieux de deplacer dans un dossier qui a un rapport avec

2024-11-25 20:11 UTC, StevyMarlino commented on app/Livewire/ReviewsList.php
> +        $this->averageRating = floatval($this->product->averageRating()[0]) ?? $this->averageRating;
effectivement, d accord

2024-11-25 20:37 UTC, mckenziearts commented on app/Livewire/ReviewsList.php
> +class ReviewsList extends SlideOverComponent
Meme si tu as une modal pour creer un produit tu dois mettre ca dans un dossier `Modals/Product` On range les composants par type

2024-11-25 21:27 UTC, StevyMarlino commented on app/Livewire/Pages/Product/SingleProduct.php
comme ca revient a manage les produits j ai trouver judicieux de deplacer dans un dossier qui a un rapport avec

2024-11-25 21:29 UTC, StevyMarlino commented on resources/views/livewire/pages/product/single-product.blade.php
> +                                    <div
la je ne saurai te le dire

2024-12-03 08:58 UTC, mckenziearts requested changes

2024-12-03 08:58 UTC, mckenziearts commented on resources/views/livewire/review-stats.blade.php
> +    #[On('reviewCreated')]
retirer le `#[On]`

2024-12-03 08:58 UTC, mckenziearts commented on resources/views/livewire/review-stats.blade.php
> +
Rajouter le declare_strict

2024-12-03 08:58 UTC, mckenziearts commented on resources/views/livewire/product/reviews.blade.php
> +                                                @for ($i = 1; $i <= 5; $i++)
utiliser le composant `x-rate-stars`

2024-12-03 08:58 UTC, mckenziearts commented on resources/views/livewire/product/reviews.blade.php
> +
Ajouter le declare strict

2024-12-03 08:58 UTC, mckenziearts commented on resources/views/livewire/modals/reviews-list.blade.php
>                                              @for ($i = 1; $i <= 5; $i++)
utiliser le composant `x-rate-stars`

2024-12-05 08:56 UTC, mckenziearts requested changes

2024-12-05 08:56 UTC, mckenziearts commented on app/Livewire/Pages/SingleProduct.php
> +        ]);
Pourquoi avoir supprimer le titre de la page?

2024-12-05 08:56 UTC, mckenziearts commented on database/seeders/DatabaseSeeder.php
> +        $this->call(ReviewSeeder::class);
Un espace avant d'appeler le seeder

2024-12-05 08:56 UTC, mckenziearts commented on database/seeders/ReviewSeeder.php
> +        $faker = Factory::create();
Pourquoi avoir définir ici ? Dans le for tu peux aussi faire `faker()->realText()` si je me trompe pas

2024-12-05 08:56 UTC, mckenziearts commented on resources/views/livewire/modals/product/add-product-review.blade.php
> +    @saved="$refresh"
Tu t'es rassuré que le modal composant accepte d'autres attributs ?

2024-12-05 08:56 UTC, mckenziearts commented on resources/views/livewire/modals/product/add-product-review.blade.php
> +                        <svg wire:click="update('{{$i}}')" class="size-5 shrink-0 {{ $i <= $form->rating ? 'text-yellow-400' : 'text-gray-300' }}" viewBox="0 0 20 20" fill="currentColor" aria-hidden=
il faut utiliser la directive `@class` pour rendre ce code plus lisible

2024-12-05 08:56 UTC, mckenziearts commented on resources/views/livewire/modals/reviews-list.blade.php
> +        @php $reviews = $this->productReviews->reviews @endphp
Tu peux mettre cette variable tout en haut du fichier et mettre un espace avec le reste du contenu

2024-12-05 08:56 UTC, mckenziearts commented on app/Livewire/Forms/ProductReviewsForm.php
> +final class ProductReviewsForm extends Form
Pourquoi la préférence de créer un Form livewire au lieu de mettre tout dans le même composant ?

2024-12-05 08:56 UTC, mckenziearts commented on app/Livewire/Forms/ProductReviewsForm.php
> +    public ?Product $product = null;
Il y'a des possibilité que cette variable soit nulle? Et aussi pourquoi la déclarer ici si elle n'est pas utilisée ?

2024-12-05 08:56 UTC, mckenziearts commented on app/Livewire/Modals/Product/AddProductReview.php
> +            'title' => __('Add new review'),
Pourquoi déclarer cette variable ici pourtant tu peux directement la mettre dans la vue?

2024-12-05 09:04 UTC, StevyMarlino commented on database/seeders/ReviewSeeder.php
> +        $faker = Factory::create();
ah oui c est plutôt fake() j j'ai d abord tester avec le helper faker mais il y avait des erreur c 'est okay now

2024-12-05 09:07 UTC, StevyMarlino commented on resources/views/livewire/modals/product/add-product-review.blade.php
> +    @saved="$refresh"
```js
@props([
    'formAction' => false,
    'headerClasses' => '',
    'contentClasses' => 'p-4 sm:p-6',
    'footerClasses' => 'p-4 sm:flex sm:p-6',
])
```
oui oui. et puis je me suis plus baser sur le composant du card

2024-12-05 09:09 UTC, mckenziearts commented on resources/views/livewire/modals/product/add-product-review.blade.php
> +    @saved="$refresh"
Non je parle du composants en lui meme. Est-ce qu'il y'a un `$attributes->merge()` dans la div du composant là

2024-12-05 09:13 UTC, StevyMarlino commented on resources/views/livewire/modals/product/add-product-review.blade.php
> +                        <svg wire:click="update('{{$i}}')" class="size-5 shrink-0 {{ $i <= $form->rating ? 'text-yellow-400' : 'text-gray-300' }}" viewBox="0 0 20 20" fill="currentColor" aria-hidden=
bon perso je pense que ce n'est pas encore assez long pour dire qu'on l utilise a ce niveau sur l écran c'est encore assez court ! est ce vraiment nécessaire ?

2024-12-05 09:15 UTC, StevyMarlino commented on app/Livewire/Forms/ProductReviewsForm.php
> +final class ProductReviewsForm extends Form
Juste separer la logique de validation de celle du composant principale d ajout.

2024-12-05 09:22 UTC, StevyMarlino commented on app/Livewire/Forms/ProductReviewsForm.php
> +    public ?Product $product = null;
effectivement pas de possibilité qu'elle soit null ! et elle est utilisé lorsque j add le review

2024-12-05 09:26 UTC, StevyMarlino commented on app/Livewire/Modals/Product/AddProductReview.php
> +            'title' => __('Add new review'),
ah oui c est vrai; je trouvais juste xa bien de passer comme xa

2024-12-05 09:29 UTC, StevyMarlino commented on resources/views/livewire/modals/reviews-list.blade.php
> +        @php $reviews = $this->productReviews->reviews @endphp
oki

2024-12-05 09:59 UTC, mckenziearts requested changes

2024-12-05 09:59 UTC, mckenziearts commented on app/Livewire/Forms/ProductReviewsForm.php
> +final class ProductReviewsForm extends Form
Parce qu'après c'est toujours plus de code à lire si tu crée un Form c'est pour que tu puisses gérer tout ce qui concerné le formulaire parce qu'en l'état je pense qu'on peut bien mettre ça dans le composant modal et ca ne change rien sur la logique

2024-12-05 09:59 UTC, mckenziearts commented on resources/views/livewire/modals/product/add-product-review.blade.php
> +                        <svg wire:click="update('{{$i}}')" class="size-5 shrink-0 {{ $i <= $form->rating ? 'text-yellow-400' : 'text-gray-300' }}" viewBox="0 0 20 20" fill="currentColor" aria-hidden=
C'est pas que ce soit long c'est que ce soit plus facile a comprendre.  Quand il y'a déjà des conditions pour afficher une classe c'est mieux d'utiliser la directive

2024-12-05 13:13 UTC, StevyMarlino commented on resources/views/livewire/modals/product/add-product-review.blade.php
> +                        <svg wire:click="update('{{$i}}')" class="size-5 shrink-0 {{ $i <= $form->rating ? 'text-yellow-400' : 'text-gray-300' }}" viewBox="0 0 20 20" fill="currentColor" aria-hidden=
d accord

2024-12-05 14:45 UTC, mckenziearts approved these changes

2024-12-05 14:45 UTC, merged